### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by 1shevelov** [kuking/WaterSortPuzzleSolver#1]
Hello,

sorry, I'm a newbie in Linux and can't Go at all, so probably that is not your issue, but I will appreciate the help.

I can't build a project with "go test" or "go build -o WSPZ"
Getting error: "build github.com/kukino/WaterSortPuzzleSolver: cannot load hash/maphash: malformed module path "hash/maphash": missing dot in first path element"

go version go1.13.8 linux/amd64

P.S. Can't solve level 705 in Water Sort Puzzle by IEC Global Pty Ltd in [Play market](https://play.google.com/store/apps/details?id=com.gma.water.sort.puzzle)

![Screenshot_20210626-135458](https://user-images.githubusercontent.com/30589388/123510928-e754fb00-d686-11eb-8c43-9bf2cb1e40df.png)

**Comment by loloyd** [comment]
Hello, kuking.  I am also suffering from the same problem.  Here's what happens on my end.

`loloyd@LD-S540:~/Projects/WaterSortPuzzleSolver$ lscpu | grep "Model name"
Model name:                      AMD Ryzen 7 4800U with Radeon Graphics
loloyd@LD-S540:~/Projects/WaterSortPuzzleSolver$ make
go clean -testcache -cache
rm -f WSPZ
go test
build github.com/kukino/WaterSortPuzzleSolver: cannot load hash/maphash: malformed module path "hash/maphash": missing dot in first path element
make: *** [Makefile:11: test] Error 1
`

Do you have any directions that you can point to us to be able to try to fix this? I also have this on my golang installation:

`loloyd@LD-S540:~/Projects/WaterSortPuzzleSolver$ go version
go version go1.13.8 linux/amd64
`

**Comment by loloyd** [comment]
1shevelov, can you please edit this issue and assign it to kuking so he/she may be able to address it better?  Thank you.

**Comment by 1shevelov** [comment]
> assign it to kuking

Don't know how I can do this, except maybe call to @kuking

**Comment by kuking** [comment]
Hi 👋 the project uses go dependencies; I understand you need at least go 1.4 for them. Let me know if that fixes it.

**Comment by 1shevelov** [comment]
> you need at least go 1.4 for them.

Not sure I understand 'at least', here. We both have 1.13 ...
Go 1.4 was released 7 years ago...

**Comment by kuking** [comment]
I beg my pardon, I meant 1.14

**Comment by 1shevelov** [comment]
Yep, worked! It solved 705 for me!

@loloyd, I've installed 1.16.5 from [official website](https://golang.org/doc/install). Be sure to delete your previous version, my Go apt-get packet was installed at /usr/lib/go1-13


@kuking Thank you! 
Maybe add Go 1.14 as a requirement to README.

P.S. Would you be interested in making a new Water Puzzle app with unique ideas, among which are tubes of different sizes and a bottom faucet (at least I haven't found these implemented anywhere)?
Please check [my post](https://shevelev.net/blog/en/test-tubes/) on it with a playable prototype (at the end). The prototype has 4 of these unique levels and the ability to create and play your own level with these new ideas.
Write me at shevelov@gmail.com

**Comment by kuking** [comment]
I will add Go 1.14 in the README as dependency. Reading your blog. Thank you for the feedback.
