### ISSUE TITLE
Process WSPZ killed after memory exceeded

### ISSUE THREAD

**Issue by plix1014** [kuking/WaterSortPuzzleSolver#2]
I try to solve level 209, but OS kills the process after memory is exceeded.
Seems process is not freeing memory.
Same on Linux and MacOS.
[os_linux.txt](https://github.com/kuking/WaterSortPuzzleSolver/files/7064548/os_linux.txt)
[os_macos.txt](https://github.com/kuking/WaterSortPuzzleSolver/files/7064549/os_macos.txt)
[s209_linux.txt](https://github.com/kuking/WaterSortPuzzleSolver/files/7064551/s209_linux.txt)
[s209_macos.txt](https://github.com/kuking/WaterSortPuzzleSolver/files/7064552/s209_macos.txt)
[main.go.txt](https://github.com/kuking/WaterSortPuzzleSolver/files/7064560/main.go.txt)
[solver.go.txt](https://github.com/kuking/WaterSortPuzzleSolver/files/7064561/solver.go.txt)

ps: in solver.go I changed just line 61 (cosmetic change).

**Comment by timoid** [comment]
disable shortest check and it returns a result nearly instantly. must be something about that level that trips up the short search algorithm.

**Comment by plix1014** [comment]
It worked, thanks.

Am Di., 14. Juni 2022 um 14:36 Uhr schrieb timoid ***@***.***
